package tests.com.csis3275;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class CustomerOrderTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
    driver = new ChromeDriver();
    //Wait at least 10 seconds for each page load
  	driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  
  @Test
  public void customerOrderTest() {
    driver.get("http://localhost:8080/food-delivery-430am/");
    driver.manage().window().setSize(new Dimension(1477, 842));
    
    vars.put("window_handles", driver.getWindowHandles());
    
    driver.findElement(By.linkText("Sign In")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("shiny7@student.douglascollege.ca");
    driver.findElement(By.id("password")).sendKeys("qwerty1234");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("View All")).click();
    driver.findElement(By.linkText("Good Fast Food")).click();
    
    //add 2 fried chickens
    driver.findElement(By.id("qty0")).click();
    driver.findElement(By.id("qty0")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("qty0")).sendKeys("2");
    //click anywhere on the screen to activate the add button
    driver.findElement(By.cssSelector(".col-md-4")).click();
    driver.findElement(By.id("addBtn0")).click();
    
    vars.put("win6256", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6256").toString());
    
    //add 1 Hawaiian pizza
    driver.findElement(By.id("qty1")).click();
    driver.findElement(By.id("qty1")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("qty1")).sendKeys("1");
    driver.findElement(By.cssSelector(".col-md-4")).click();
    driver.findElement(By.id("addBtn1")).click();
    
    vars.put("win6256", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6256").toString());
    
    //delete Hawaiian pizza
    driver.findElement(By.cssSelector(".list-group-item:nth-child(2) path")).click();

    vars.put("win6256", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6256").toString());
    
    //add 1 pepperoni pizza
    driver.findElement(By.id("qty2")).click();
    driver.findElement(By.id("qty2")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("qty2")).sendKeys("1");
    driver.findElement(By.cssSelector(".col-md-4")).click();
    driver.findElement(By.id("addBtn2")).click();
    
    vars.put("win6256", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6256").toString());
    
    //add 1 coke
    driver.findElement(By.id("qty3")).click();
    driver.findElement(By.id("qty3")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("qty3")).sendKeys("1");
    driver.findElement(By.cssSelector(".col-md-4")).click();
    driver.findElement(By.id("addBtn3")).click();
    
    vars.put("win6256", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6256").toString());
    
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Yerin Shin")).click();
    driver.findElement(By.linkText("Order History")).click();
    
    vars.put("win6256", waitForWindow(5000));
    driver.switchTo().window(vars.get("win6256").toString());
    
    assertEquals(driver.findElement(By.cssSelector(".col-md-4:nth-child(1) .card:nth-child(4)")).getText(), "Fried Chicken");
    assertEquals(driver.findElement(By.cssSelector(".col-md-4:nth-child(1) .card:nth-child(5)")).getText(), "Pepperoni Pizza");
    assertEquals(driver.findElement(By.cssSelector(".col-md-4:nth-child(1) .card:nth-child(6)")).getText(), "Coka Cola");
  }
}
